import type { Metadata } from "next";
import "./globals.css";
import Header from "@/layouts/header/Header";
import Provider from "@/provider/reactQuery";

export const metadata: Metadata = {
  title: "Redux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="">
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
